### ISSUE TITLE
Pulsar chart version 1.0.10 is no longer available

### ISSUE THREAD

**Issue by ncmans** [kafkaesque-io/pulsar-helm-chart#11]
Seems like after the 1.0.11 release, the helm repo index no longer has 1.0.10. We kind of expected all versions to remain in the repo, or at least several recent versions:

```
$ helm search repo --versions kafkaesque/pulsar --devel 
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                                    
kafkaesque/pulsar        	1.0.11       	1.0        	Apache Pulsar Helm chart for Kubernetes        
kafkaesque/pulsar-monitor	0.1.0        	1.0        	A Helm chart for the Pulsar Monitor application
```

This broke our scripts that were re-installing the chart.

**Comment by cdbartholomew** [comment]
@ncmans this is a problem with the automated build process which updates the index.yaml file for the repository. We still have the releases, they just aren't in the index. I will look into it.

**Comment by cdbartholomew** [comment]
@ncmans I have fixed this by repairing the index.yaml. The root cause was a broken release script, which I have already fixed. I confirmed that the release process no longer deletes the older releases from the index.yaml, so you shouldn't see this in the future.

**Comment by ncmans** [comment]
Thanks @cdbartholomew  — checked and it's fixed. Closing.
