### ISSUE TITLE
Accept Storage Class Name

### ISSUE THREAD

**Issue by ncmans** [kafkaesque-io/pulsar-helm-chart#14]
Currently, one has to specify storage class _definitions_ at one/more of these places:

* `default_storage`
* `zookeeper.volumes.data.storageClass`
* `bookkeeper.volumes.journal.storageClass`
* `bookkeeper.volumes.ledgers.storageClass`
* `function.volumes.ledgers.storageClass`
* `stateStorage.volumes.data.storageClass`
* `prometheus.volumes.data.storageClass`

To keep in line with general conventions and make the chart more flexible, it'd be better if instead of accepting definitions and creating storage class resources, the chart simply accepts storage class names.

Here are some stable charts that accept storage class names:

* [CockroachDB](https://github.com/helm/charts/blob/958e01a4d70d8739003c24dd132d47ec2d359b46/stable/cockroachdb/templates/statefulset.yaml#L325)
* [MariaDB](https://github.com/helm/charts/blob/958e01a4d70d8739003c24dd132d47ec2d359b46/stable/mariadb/templates/_helpers.tpl#L213)
* [Redis](https://github.com/helm/charts/blob/958e01a4d70d8739003c24dd132d47ec2d359b46/stable/redis/templates/_helpers.tpl#L290)

**Comment by cdbartholomew** [comment]
@ncmans Good suggestion. I look at the examples and see if we can use the same pattern here.

**Comment by ncmans** [comment]
Fixed by https://github.com/kafkaesque-io/pulsar-helm-chart/pull/22
