### ISSUE TITLE
Documentation unclear on Authentication token

### ISSUE THREAD

**Issue by haris-zynka** [kafkaesque-io/pulsar-helm-chart#27]
I've setup everything as described in README.md but for some reason as soon as the pulsar starts nothing requires JWT for communcation. Does anyone know why?

UPDATE: As discussed it appears that documentation is "incorrect" in a way that Authentication by JWT is enabled. It is configured to work with it but not enabled by default

**Comment by cdbartholomew** [comment]
Have you turned on token-based auth? It's off by default:

```
# Enable token-based authentication and authorization
enableTokenAuth: no
```

**Comment by haris-zynka** [comment]
> Have you turned on token-based auth? It's off by default:
> 
> ```
> # Enable token-based authentication and authorization
> enableTokenAuth: no
> ```

Thank you so much. By reading 

> Authentication
> The cluster is configured to use token-based authentication.

in README.md I assumed it's already configured as specified.

**Comment by cdbartholomew** [comment]
I will clarify the docs.

**Comment by cdbartholomew** [comment]
@haris-zynka I have updated the Authentication section of README.md to hopefully clarify this. Please take a look and let me know if it resolves the issue.

**Comment by haris-zynka** [comment]
> @haris-zynka I have updated the Authentication section of README.md to hopefully clarify this. Please take a look and let me know if it resolves the issue.

Yes, this was the thing missing. Thank you.
