### ISSUE TITLE
unknown field "readonly" in VolumeMount in case to enableTokenAuth is true

### ISSUE THREAD

**Issue by gaborho** [kafkaesque-io/pulsar-helm-chart#7]
Hi Chris, 

I get the following error in case I set enableTokenAuth: yes in Helm values file:

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[0]): unknown field "readonly" in io.k8s.api.core.v1.Vol
umeMount, ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[1]): unknown field "readonly" in io.k8s.api.core.v1.VolumeMount, ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[2]): unknown fiel
d "readonly" in io.k8s.api.core.v1.VolumeMount, ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[3]): unknown field "readonly" in io.k8s.api.core.v1.VolumeMount]`

readonly should be changed to readOnly in every template. 
Let me know if I should send a PR.

Thanks,

Regards,
Gabor

**Comment by cdbartholomew** [comment]
Hi Gabor, 

If you could send a PR, that would be great!

Thanks,
Chris

**Comment by gaborho** [comment]
Hi @cdbartholomew 
I opened PR https://github.com/kafkaesque-io/pulsar-helm-chart/pull/8
