### ISSUE TITLE
Helm 3.4 install issue when enabling pulsarexpress or pulsarBeam

### ISSUE THREAD

**Issue by yabinmeng** [kafkaesque-io/pulsar-helm-chart#71]
Hi,

I'm using latest Helm (3.4) to deploy a Pulsar cluster on GKE. 

When I enable pulsarexpress, the helm install returns the following error:
`Error: template: pulsar/templates/pulsar-express-deployment.yaml:58:11: executing "pulsar/templates/pulsar-express-deployment.yaml" at <(.Values.nodeSelector) and (eq .Values.pulsarexpress.nodeSelector false)>: can't give argument to non-function .Values.nodeSelector`

A similar issue when I enable pulsarBeam:
`Error: template: pulsar/templates/beamwh-deployment.yaml:53:11: executing "pulsar/templates/beamwh-deployment.yaml" at <(.Values.nodeSelector) and (eq .Values.pulsarBeam.nodeSelector false)>: can't give argument to non-function .Values.nodeSelector`

**Comment by zzzming** [comment]
We have to fix the template because since go 1.14 has introduced this ( https://golang.org/doc/go1.14 )
```
The text/template package now correctly reports errors when a parenthesized argument is used as a function. This most commonly shows up in erroneous cases like {{if (eq .F "a") or (eq .F "b")}}. This should be written as {{if or (eq .F "a") (eq .F "b")}}. The erroneous case never worked as expected, and will now be reported with an error can't give argument to non-function.
```
helm3.4 is based on go1.14.10

**Comment by yabinmeng** [comment]
helm 3.3+ is based on go 1.14
helm 3.2.4 is working fine (go 1.13)

**Comment by cdbartholomew** [comment]
@yabinmeng I am pretty sure this is addressed in the latest version of the chart, so I am going to close. Please re-open if you are still seeing an issue.
