### ISSUE TITLE
Tiered Storage on GCP

### ISSUE THREAD

**Issue by ncmans** [kafkaesque-io/pulsar-helm-chart#9]
I'm trying to figure out what the value of following needs to be:

https://github.com/kafkaesque-io/pulsar-helm-chart/blob/5bdd115009c5c70cc0223728882f125cedef5576/helm-chart-sources/pulsar/values.yaml#L151

I can't even find a reference to this in the chart templates. Could you please provide some guidance. Thanks.

**Comment by cdbartholomew** [comment]
Hi, @ncmans. I looked into getting you some sample values, but it seems we are missing the ability to configure the Google Service account JSON file that is needed for authentication. I will fix that then get you a sample set of values.

**Comment by cdbartholomew** [comment]
@ncmans Created a new release 1.0.11 of the chart. It now properly supports GCP tiered storage. Also it has (hopefully) improved the comments in the values file. The key thing to note for GCP is you have to upload the JSON file with the credentials for your GCP service account into a Kubernetes secret for this all to work:

```
storageOffload: {}
  ## General
  ## =======
  # bucket: <bucket>
  # region: <region>
  # maxBlockSizeInBytes: "64000000" 
  # readBufferSizeInBytes: "1000000"
  ## The following are default values for the cluster. They can be changed
  ## on each namespace.
  # managedLedgerOffloadDeletionLagMs: "14400000"
  # managedLedgerOffloadAutoTriggerSizeThresholdBytes: "1000000"

  # For AWS S3
  # ======
  # You must create an IAM account with access to the bucket and 
  # generate keys for that account.
  #
  # driver: aws-s3
  # accessKey: <access-key>
  # accessSecret: <secret-key>
  ## For s3 compatible services, need to specify the endpoint but
  ## not needed for AWS
  # serviceEndpoint: s3-compatible

  ## For Google Cloud Storage
  ## ====================
  ## You must create a service account that has access to the objects in GCP buckets
  ## and upload its key as a JSON file to a secret.
  ## 
  ## 1. Go to https://console.cloud.google.com/iam-admin/serviceaccounts
  ## 2. Select your project.
  ## 3. Create a new service account.
  ## 4. Give the service account permission to access the bucket. For example, 
  ##    the "Storage Object Admin" role.
  ## 5. Create a key for the service account and save it as a JSON file.
  ## 6. Save the JSON file in a secret:
  ##       kubectl create secret generic pulsar-gcp-sa-secret \
  ##          --from-file=kafkaesque-223201-f12856532197.json \
  ##          --namespace pulsar
  ## 
  # driver: google-cloud-storage
  # gcsServiceAccountSecret: pulsar-gcp-sa-secret
  # gcsServiceAccountJsonFile: kafkaesque-223201-f12856532197.json
```

**Comment by ncmans** [comment]
@cdbartholomew Thank you so much for the speedy response and speedier resolution. Will give it a shot soon and will close the issue if all good.

**Comment by ncmans** [comment]
Gave it a shot and I'm getting this error:

```
Caused by: java.io.IOException: No offloader found for driver 'google-cloud-storage'. Please make sure you dropped the offloader nar packages under `${PULSAR_HOME}/offloaders`.
	at org.apache.bookkeeper.mledger.offload.Offloaders.getOffloaderFactory(Offloaders.java:42) ~[org.apache.pulsar-managed-ledger-2.5.0.jar:2.5.0]
	at org.apache.pulsar.broker.PulsarService.createManagedLedgerOffloader(PulsarService.java:775) ~[org.apache.pulsar-pulsar-broker-2.5.0.jar:2.5.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:401) ~[org.apache.pulsar-pulsar-broker-2.5.0.jar:2.5.0]
```

**Comment by cdbartholomew** [comment]
@ncmans You need to make sure you are running with the `pulsar-all` image on the broker when using tiered storage. The `pulsar` image doesn't contain the drivers.

**Comment by ncmans** [comment]
I see. Shouldn't the chart pick the right image automatically when tiered storage is enabled?

**Comment by cdbartholomew** [comment]
I think the best thing to do is to default the broker image to pulsar-all, assuming most people will want to use tiered storage at some point.

**Comment by ncmans** [comment]
> I think the best thing to do is to default the broker image to pulsar-all, assuming most people will want to use tiered storage at some point.

Ye, I was thinking that too. Perhaps a comment in the `values.yaml` file can mention `pulsar` image as being a more lightweight alternative for when tiered storage is not needed.

**Comment by ncmans** [comment]
Tested this and it seems to work OK. Thanks @cdbartholomew for quick resolution. Closing.
